### ISSUE TITLE
configuration file cannot specify days + seconds

### ISSUE THREAD

**Issue by breezykermo** [scztt/frame#3]
When specifying a day **and** an "HH:MM:SS" string, the event doesn't seem to be triggered appropriately.

For example:
```yaml
events:
  # plays as expected
  saturday_1pm:
    name: ev1
    type: PlayVideo
    schedule: every().saturday.at("13:00")
    url: file:///videos/v1.mp4
  # doesn't play
  saturday_on_the_second:
    name: ev2
    type: PlayVideo
    schedule: every().saturday.at("13:01:12")
    url: file:///videos/v2.mp4
```

I think (although am not 100%) that this is a bug/insufficiency in the underlying python library [schedule](https://github.com/dbader/schedule).
